// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Domains
{
    public static class ListDomainSnapshots
    {
        public static Task<Outputs.ListDomainSnapshotsProperties> InvokeAsync(ListDomainSnapshotsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.ListDomainSnapshotsProperties>("constellix:domains:listDomainSnapshots", args ?? new ListDomainSnapshotsArgs(), options.WithDefaults());

        public static Output<Outputs.ListDomainSnapshotsProperties> Invoke(ListDomainSnapshotsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.ListDomainSnapshotsProperties>("constellix:domains:listDomainSnapshots", args ?? new ListDomainSnapshotsInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListDomainSnapshotsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        public ListDomainSnapshotsArgs()
        {
        }
        public static new ListDomainSnapshotsArgs Empty => new ListDomainSnapshotsArgs();
    }

    public sealed class ListDomainSnapshotsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        public ListDomainSnapshotsInvokeArgs()
        {
        }
        public static new ListDomainSnapshotsInvokeArgs Empty => new ListDomainSnapshotsInvokeArgs();
    }
}
