// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Domains
{
    public static class ListDomainRecords
    {
        public static Task<Outputs.ListDomainRecordsProperties> InvokeAsync(ListDomainRecordsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.ListDomainRecordsProperties>("constellix:domains:listDomainRecords", args ?? new ListDomainRecordsArgs(), options.WithDefaults());

        public static Output<Outputs.ListDomainRecordsProperties> Invoke(ListDomainRecordsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.ListDomainRecordsProperties>("constellix:domains:listDomainRecords", args ?? new ListDomainRecordsInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListDomainRecordsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        public ListDomainRecordsArgs()
        {
        }
        public static new ListDomainRecordsArgs Empty => new ListDomainRecordsArgs();
    }

    public sealed class ListDomainRecordsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        public ListDomainRecordsInvokeArgs()
        {
        }
        public static new ListDomainRecordsInvokeArgs Empty => new ListDomainRecordsInvokeArgs();
    }
}
