// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.CONSTELLIX.Templates
{
    /// <summary>
    /// Optional region for this record. Will default to 'default'.
    /// </summary>
    [EnumType]
    public readonly struct TemplateRecordPropertiesRegion : IEquatable<TemplateRecordPropertiesRegion>
    {
        private readonly string _value;

        private TemplateRecordPropertiesRegion(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static TemplateRecordPropertiesRegion Default { get; } = new TemplateRecordPropertiesRegion("default");
        public static TemplateRecordPropertiesRegion Europe { get; } = new TemplateRecordPropertiesRegion("europe");
        public static TemplateRecordPropertiesRegion UsEast { get; } = new TemplateRecordPropertiesRegion("us-east");
        public static TemplateRecordPropertiesRegion UsWest { get; } = new TemplateRecordPropertiesRegion("us-west");
        public static TemplateRecordPropertiesRegion AsiaPacific { get; } = new TemplateRecordPropertiesRegion("asia-pacific");
        public static TemplateRecordPropertiesRegion Oceania { get; } = new TemplateRecordPropertiesRegion("oceania");
        public static TemplateRecordPropertiesRegion SouthAmerica { get; } = new TemplateRecordPropertiesRegion("south-america");

        public static bool operator ==(TemplateRecordPropertiesRegion left, TemplateRecordPropertiesRegion right) => left.Equals(right);
        public static bool operator !=(TemplateRecordPropertiesRegion left, TemplateRecordPropertiesRegion right) => !left.Equals(right);

        public static explicit operator string(TemplateRecordPropertiesRegion value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is TemplateRecordPropertiesRegion other && Equals(other);
        public bool Equals(TemplateRecordPropertiesRegion other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
