// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listIPFilters(args?: ListIPFiltersArgs, opts?: pulumi.InvokeOptions): Promise<outputs.ipfilters.ListIPFiltersProperties> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:ipfilters:listIPFilters", {
    }, opts);
}

export interface ListIPFiltersArgs {
}
export function listIPFiltersOutput(opts?: pulumi.InvokeOptions): pulumi.Output<outputs.ipfilters.ListIPFiltersProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:ipfilters:listIPFilters", {
    }, opts);
}

