// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vanitynameservers

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListVanityNameservers(ctx *pulumi.Context, args *ListVanityNameserversArgs, opts ...pulumi.InvokeOption) (*ListVanityNameserversResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListVanityNameserversResult
	err := ctx.Invoke("constellix:vanitynameservers:listVanityNameservers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListVanityNameserversArgs struct {
}

type ListVanityNameserversResult struct {
	Data []VanitynameserverType `pulumi:"data"`
	// Metadata for list responses
	Meta *ListMetadata `pulumi:"meta"`
}

func ListVanityNameserversOutput(ctx *pulumi.Context, args ListVanityNameserversOutputArgs, opts ...pulumi.InvokeOption) ListVanityNameserversResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListVanityNameserversResultOutput, error) {
			args := v.(ListVanityNameserversArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv ListVanityNameserversResult
			secret, err := ctx.InvokePackageRaw("constellix:vanitynameservers:listVanityNameservers", args, &rv, "", opts...)
			if err != nil {
				return ListVanityNameserversResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(ListVanityNameserversResultOutput)
			if secret {
				return pulumi.ToSecret(output).(ListVanityNameserversResultOutput), nil
			}
			return output, nil
		}).(ListVanityNameserversResultOutput)
}

type ListVanityNameserversOutputArgs struct {
}

func (ListVanityNameserversOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListVanityNameserversArgs)(nil)).Elem()
}

type ListVanityNameserversResultOutput struct{ *pulumi.OutputState }

func (ListVanityNameserversResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListVanityNameserversResult)(nil)).Elem()
}

func (o ListVanityNameserversResultOutput) ToListVanityNameserversResultOutput() ListVanityNameserversResultOutput {
	return o
}

func (o ListVanityNameserversResultOutput) ToListVanityNameserversResultOutputWithContext(ctx context.Context) ListVanityNameserversResultOutput {
	return o
}

func (o ListVanityNameserversResultOutput) Data() VanitynameserverTypeArrayOutput {
	return o.ApplyT(func(v ListVanityNameserversResult) []VanitynameserverType { return v.Data }).(VanitynameserverTypeArrayOutput)
}

// Metadata for list responses
func (o ListVanityNameserversResultOutput) Meta() ListMetadataPtrOutput {
	return o.ApplyT(func(v ListVanityNameserversResult) *ListMetadata { return v.Meta }).(ListMetadataPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ListVanityNameserversResultOutput{})
}
