// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Contactlists.Outputs
{

    /// <summary>
    /// Lists of email addresses used for notifications and messages about domains and records.
    /// </summary>
    [OutputType]
    public sealed class Contactlist
    {
        /// <summary>
        /// The number of emails in this contact list
        /// </summary>
        public readonly int? EmailCount;
        /// <summary>
        /// The emails in this list
        /// </summary>
        public readonly ImmutableArray<Outputs.ContactlistEmailsItemProperties> Emails;
        /// <summary>
        /// Unique ID for the contact list
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Links for the object
        /// </summary>
        public readonly Outputs.ContactlistLinksProperties? Links;
        /// <summary>
        /// A name for this contact list
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private Contactlist(
            int? emailCount,

            ImmutableArray<Outputs.ContactlistEmailsItemProperties> emails,

            int? id,

            Outputs.ContactlistLinksProperties? links,

            string? name)
        {
            EmailCount = emailCount;
            Emails = emails;
            Id = id;
            Links = links;
            Name = name;
        }
    }
}
