// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Contactlists.Outputs
{

    [OutputType]
    public sealed class ContactlistTeams
    {
        /// <summary>
        /// The channel to send the message to
        /// </summary>
        public readonly string? Channel;
        public readonly Outputs.ContactlistTeamsContactlistProperties? Contactlist;
        public readonly int? Id;
        /// <summary>
        /// Links for the MS Teams Webhook
        /// </summary>
        public readonly Outputs.ContactlistTeamsLinksProperties? Links;
        /// <summary>
        /// The inbound webhook URL for MS Teams
        /// </summary>
        public readonly string? Webhook;

        [OutputConstructor]
        private ContactlistTeams(
            string? channel,

            Outputs.ContactlistTeamsContactlistProperties? contactlist,

            int? id,

            Outputs.ContactlistTeamsLinksProperties? links,

            string? webhook)
        {
            Channel = channel;
            Contactlist = contactlist;
            Id = id;
            Links = links;
            Webhook = webhook;
        }
    }
}
