// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains
{
    public static class GetCNAME
    {
        public static Task<Outputs.GetCNAME> InvokeAsync(GetCNAMEArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.GetCNAME>("constellix:domains:getCNAME", args ?? new GetCNAMEArgs(), options.WithDefaults());

        public static Output<Outputs.GetCNAME> Invoke(GetCNAMEInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.GetCNAME>("constellix:domains:getCNAME", args ?? new GetCNAMEInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCNAMEArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetCNAMEArgs()
        {
        }
        public static new GetCNAMEArgs Empty => new GetCNAMEArgs();
    }

    public sealed class GetCNAMEInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetCNAMEInvokeArgs()
        {
        }
        public static new GetCNAMEInvokeArgs Empty => new GetCNAMEInvokeArgs();
    }
}
