// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains
{
    public static class GetHttp
    {
        public static Task<Outputs.GetHttp> InvokeAsync(GetHttpArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.GetHttp>("constellix:domains:getHttp", args ?? new GetHttpArgs(), options.WithDefaults());

        public static Output<Outputs.GetHttp> Invoke(GetHttpInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.GetHttp>("constellix:domains:getHttp", args ?? new GetHttpInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHttpArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetHttpArgs()
        {
        }
        public static new GetHttpArgs Empty => new GetHttpArgs();
    }

    public sealed class GetHttpInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetHttpInvokeArgs()
        {
        }
        public static new GetHttpInvokeArgs Empty => new GetHttpInvokeArgs();
    }
}
