// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains
{
    public static class GetTXT
    {
        public static Task<Outputs.GetTXT> InvokeAsync(GetTXTArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.GetTXT>("constellix:domains:getTXT", args ?? new GetTXTArgs(), options.WithDefaults());

        public static Output<Outputs.GetTXT> Invoke(GetTXTInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.GetTXT>("constellix:domains:getTXT", args ?? new GetTXTInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTXTArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public string DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetTXTArgs()
        {
        }
        public static new GetTXTArgs Empty => new GetTXTArgs();
    }

    public sealed class GetTXTInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the domain object
        /// </summary>
        [Input("domainId", required: true)]
        public Input<string> DomainId { get; set; } = null!;

        /// <summary>
        /// The ID of the record
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetTXTInvokeArgs()
        {
        }
        public static new GetTXTInvokeArgs Empty => new GetTXTInvokeArgs();
    }
}
