// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const DomainRecordPropertiesRegion = {
    Default: "default",
    Europe: "europe",
    UsEast: "us-east",
    UsWest: "us-west",
    AsiaPacific: "asia-pacific",
    Oceania: "oceania",
    SouthAmerica: "south-america",
} as const;

/**
 * Optional region for this record. Will default to 'default'.
 */
export type DomainRecordPropertiesRegion = (typeof DomainRecordPropertiesRegion)[keyof typeof DomainRecordPropertiesRegion];

export const DomainStatus = {
    Active: "ACTIVE",
    Suspended: "SUSPENDED",
    Terminated: "TERMINATED",
} as const;

export type DomainStatus = (typeof DomainStatus)[keyof typeof DomainStatus];

export const DomainanalyticsQueriesItemPropertiesType = {
    GeoProximity: "geo_proximity",
    Standard: "standard",
    GeoFilter: "geo_filter",
} as const;

/**
 * The type of query the analytics are for
 */
export type DomainanalyticsQueriesItemPropertiesType = (typeof DomainanalyticsQueriesItemPropertiesType)[keyof typeof DomainanalyticsQueriesItemPropertiesType];

export const SimpleDomainStatus = {
    Active: "ACTIVE",
    Suspended: "SUSPENDED",
    Terminated: "TERMINATED",
} as const;

export type SimpleDomainStatus = (typeof SimpleDomainStatus)[keyof typeof SimpleDomainStatus];
