// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Templates.Inputs
{

    public sealed class ValueAaaaRequestValueItemPropertiesArgs : global::Pulumi.ResourceArgs
    {
        [Input("id")]
        public Input<int>? Id { get; set; }

        public ValueAaaaRequestValueItemPropertiesArgs()
        {
        }
        public static new ValueAaaaRequestValueItemPropertiesArgs Empty => new ValueAaaaRequestValueItemPropertiesArgs();
    }
}
