// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Templates.Outputs
{

    [OutputType]
    public sealed class ValueSrvValueItemProperties
    {
        /// <summary>
        /// Whether the entry is enabled or not. Disabled entries will not be included in a response
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// The hostname for the service
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// The port the service runs on
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// A priority for this record
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// A weight for this record
        /// </summary>
        public readonly int? Weight;

        [OutputConstructor]
        private ValueSrvValueItemProperties(
            bool? enabled,

            string? host,

            int? port,

            int? priority,

            int? weight)
        {
            Enabled = enabled;
            Host = host;
            Port = port;
            Priority = priority;
            Weight = weight;
        }
    }
}
