// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Geoproximities.Outputs
{

    [OutputType]
    public sealed class DataProperties
    {
        /// <summary>
        /// The ID of the object
        /// </summary>
        public readonly int? Id;
        public readonly Outputs.DataPropertiesLinksProperties? Links;

        [OutputConstructor]
        private DataProperties(
            int? id,

            Outputs.DataPropertiesLinksProperties? links)
        {
            Id = id;
            Links = links;
        }
    }
}
