// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Announcements
{
    /// <summary>
    /// The type of Announcement
    /// </summary>
    [EnumType]
    public readonly struct AnnouncementType : IEquatable<AnnouncementType>
    {
        private readonly string _value;

        private AnnouncementType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static AnnouncementType DashboardLinks { get; } = new AnnouncementType("DashboardLinks");

        public static bool operator ==(AnnouncementType left, AnnouncementType right) => left.Equals(right);
        public static bool operator !=(AnnouncementType left, AnnouncementType right) => !left.Equals(right);

        public static explicit operator string(AnnouncementType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is AnnouncementType other && Equals(other);
        public bool Equals(AnnouncementType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
