// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Domains.Outputs
{

    /// <summary>
    /// Some statistics for these analytics
    /// </summary>
    [OutputType]
    public sealed class DomainanalyticsQueriesItemPropertiesStatsProperties
    {
        /// <summary>
        /// The number of time periods
        /// </summary>
        public readonly int? Count;
        /// <summary>
        /// The maximum number of queries for one time period
        /// </summary>
        public readonly int? Max;
        /// <summary>
        /// The mean average number of queries per time period
        /// </summary>
        public readonly double? Mean;
        /// <summary>
        /// The minimum number of queries for one time period
        /// </summary>
        public readonly int? Min;
        /// <summary>
        /// The sum of queries for this date range
        /// </summary>
        public readonly int? Sum;

        [OutputConstructor]
        private DomainanalyticsQueriesItemPropertiesStatsProperties(
            int? count,

            int? max,

            double? mean,

            int? min,

            int? sum)
        {
            Count = count;
            Max = max;
            Mean = mean;
            Min = min;
            Sum = sum;
        }
    }
}
