// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains.Inputs
{

    /// <summary>
    /// Failover record mode
    /// </summary>
    public sealed class ValueAaaaRequestValuePropertiesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether this failover value is enabled or not
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The failover mode
        /// </summary>
        [Input("mode")]
        public Input<CloudySkySoftware.Pulumi.Constellix.Domains.ValueAaaaRequestValuePropertiesMode>? Mode { get; set; }

        [Input("values")]
        private InputList<Inputs.ValueAaaaRequestValuePropertiesValuesItemPropertiesArgs>? _values;
        public InputList<Inputs.ValueAaaaRequestValuePropertiesValuesItemPropertiesArgs> Values
        {
            get => _values ?? (_values = new InputList<Inputs.ValueAaaaRequestValuePropertiesValuesItemPropertiesArgs>());
            set => _values = value;
        }

        public ValueAaaaRequestValuePropertiesArgs()
        {
        }
        public static new ValueAaaaRequestValuePropertiesArgs Empty => new ValueAaaaRequestValuePropertiesArgs();
    }
}
