// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Ping
{
    public static class GetPing
    {
        public static Task<Outputs.Ping> InvokeAsync(GetPingArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.Ping>("constellix:ping:getPing", args ?? new GetPingArgs(), options.WithDefaults());

        public static Output<Outputs.Ping> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.Ping>("constellix:ping:getPing", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class GetPingArgs : global::Pulumi.InvokeArgs
    {
        public GetPingArgs()
        {
        }
        public static new GetPingArgs Empty => new GetPingArgs();
    }
}
