// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getRP(args: GetRPArgs, opts?: pulumi.InvokeOptions): Promise<outputs.domains.GetRP> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:domains:getRP", {
        "domainId": args.domainId,
        "id": args.id,
    }, opts);
}

export interface GetRPArgs {
    /**
     * The ID of the domain object
     */
    domainId: string;
    /**
     * The ID of the record
     */
    id: string;
}
export function getRPOutput(args: GetRPOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.domains.GetRP> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:domains:getRP", {
        "domainId": args.domainId,
        "id": args.id,
    }, opts);
}

export interface GetRPOutputArgs {
    /**
     * The ID of the domain object
     */
    domainId: pulumi.Input<string>;
    /**
     * The ID of the record
     */
    id: pulumi.Input<string>;
}
