// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listDomainSnapshots(args: ListDomainSnapshotsArgs, opts?: pulumi.InvokeOptions): Promise<outputs.domains.ListDomainSnapshotsProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:domains:listDomainSnapshots", {
        "domainId": args.domainId,
    }, opts);
}

export interface ListDomainSnapshotsArgs {
    /**
     * The ID of the domain object
     */
    domainId: string;
}
export function listDomainSnapshotsOutput(args: ListDomainSnapshotsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.domains.ListDomainSnapshotsProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:domains:listDomainSnapshots", {
        "domainId": args.domainId,
    }, opts);
}

export interface ListDomainSnapshotsOutputArgs {
    /**
     * The ID of the domain object
     */
    domainId: pulumi.Input<string>;
}
