// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export class ContactListEmail extends pulumi.CustomResource {
    /**
     * Get an existing ContactListEmail resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ContactListEmail {
        return new ContactListEmail(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'constellix:contactlists:ContactListEmail';

    /**
     * Returns true if the given object is an instance of ContactListEmail.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ContactListEmail {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ContactListEmail.__pulumiType;
    }

    /**
     * The email address
     */
    public readonly address!: pulumi.Output<string | undefined>;
    public /*out*/ readonly data!: pulumi.Output<outputs.contactlists.DataProperties | undefined>;

    /**
     * Create a ContactListEmail resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ContactListEmailArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["address"] = args ? args.address : undefined;
            resourceInputs["id"] = args ? args.id : undefined;
            resourceInputs["data"] = undefined /*out*/;
        } else {
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["data"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ContactListEmail.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ContactListEmail resource.
 */
export interface ContactListEmailArgs {
    /**
     * The email address
     */
    address?: pulumi.Input<string>;
    /**
     * The ID of the Contact List
     */
    id?: pulumi.Input<string>;
}
