// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ContactListArgs } from "./contactList";
export type ContactList = import("./contactList").ContactList;
export const ContactList: typeof import("./contactList").ContactList = null as any;
utilities.lazyLoad(exports, ["ContactList"], () => require("./contactList"));

export { ContactListEmailArgs } from "./contactListEmail";
export type ContactListEmail = import("./contactListEmail").ContactListEmail;
export const ContactListEmail: typeof import("./contactListEmail").ContactListEmail = null as any;
utilities.lazyLoad(exports, ["ContactListEmail"], () => require("./contactListEmail"));

export { ContactListSlackWebhookArgs } from "./contactListSlackWebhook";
export type ContactListSlackWebhook = import("./contactListSlackWebhook").ContactListSlackWebhook;
export const ContactListSlackWebhook: typeof import("./contactListSlackWebhook").ContactListSlackWebhook = null as any;
utilities.lazyLoad(exports, ["ContactListSlackWebhook"], () => require("./contactListSlackWebhook"));

export { ContactListTeamArgs } from "./contactListTeam";
export type ContactListTeam = import("./contactListTeam").ContactListTeam;
export const ContactListTeam: typeof import("./contactListTeam").ContactListTeam = null as any;
utilities.lazyLoad(exports, ["ContactListTeam"], () => require("./contactListTeam"));

export { ListContactArgs, ListContactOutputArgs } from "./listContact";
export const listContact: typeof import("./listContact").listContact = null as any;
export const listContactOutput: typeof import("./listContact").listContactOutput = null as any;
utilities.lazyLoad(exports, ["listContact","listContactOutput"], () => require("./listContact"));

export { ListContactEmailArgs, ListContactEmailOutputArgs } from "./listContactEmail";
export const listContactEmail: typeof import("./listContactEmail").listContactEmail = null as any;
export const listContactEmailOutput: typeof import("./listContactEmail").listContactEmailOutput = null as any;
utilities.lazyLoad(exports, ["listContactEmail","listContactEmailOutput"], () => require("./listContactEmail"));

export { ListContactEmailsArgs, ListContactEmailsOutputArgs } from "./listContactEmails";
export const listContactEmails: typeof import("./listContactEmails").listContactEmails = null as any;
export const listContactEmailsOutput: typeof import("./listContactEmails").listContactEmailsOutput = null as any;
utilities.lazyLoad(exports, ["listContactEmails","listContactEmailsOutput"], () => require("./listContactEmails"));

export { ListContactSlackWebhookArgs, ListContactSlackWebhookOutputArgs } from "./listContactSlackWebhook";
export const listContactSlackWebhook: typeof import("./listContactSlackWebhook").listContactSlackWebhook = null as any;
export const listContactSlackWebhookOutput: typeof import("./listContactSlackWebhook").listContactSlackWebhookOutput = null as any;
utilities.lazyLoad(exports, ["listContactSlackWebhook","listContactSlackWebhookOutput"], () => require("./listContactSlackWebhook"));

export { ListContactSlackWebhooksArgs, ListContactSlackWebhooksOutputArgs } from "./listContactSlackWebhooks";
export const listContactSlackWebhooks: typeof import("./listContactSlackWebhooks").listContactSlackWebhooks = null as any;
export const listContactSlackWebhooksOutput: typeof import("./listContactSlackWebhooks").listContactSlackWebhooksOutput = null as any;
utilities.lazyLoad(exports, ["listContactSlackWebhooks","listContactSlackWebhooksOutput"], () => require("./listContactSlackWebhooks"));

export { ListContactTeamArgs, ListContactTeamOutputArgs } from "./listContactTeam";
export const listContactTeam: typeof import("./listContactTeam").listContactTeam = null as any;
export const listContactTeamOutput: typeof import("./listContactTeam").listContactTeamOutput = null as any;
utilities.lazyLoad(exports, ["listContactTeam","listContactTeamOutput"], () => require("./listContactTeam"));

export { ListContactTeamsArgs, ListContactTeamsOutputArgs } from "./listContactTeams";
export const listContactTeams: typeof import("./listContactTeams").listContactTeams = null as any;
export const listContactTeamsOutput: typeof import("./listContactTeams").listContactTeamsOutput = null as any;
utilities.lazyLoad(exports, ["listContactTeams","listContactTeamsOutput"], () => require("./listContactTeams"));

export { ListContactsArgs } from "./listContacts";
export const listContacts: typeof import("./listContacts").listContacts = null as any;
export const listContactsOutput: typeof import("./listContacts").listContactsOutput = null as any;
utilities.lazyLoad(exports, ["listContacts","listContactsOutput"], () => require("./listContacts"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "constellix:contactlists:ContactList":
                return new ContactList(name, <any>undefined, { urn })
            case "constellix:contactlists:ContactListEmail":
                return new ContactListEmail(name, <any>undefined, { urn })
            case "constellix:contactlists:ContactListSlackWebhook":
                return new ContactListSlackWebhook(name, <any>undefined, { urn })
            case "constellix:contactlists:ContactListTeam":
                return new ContactListTeam(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("constellix", "contactlists", _module)
