// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listContact(args: ListContactArgs, opts?: pulumi.InvokeOptions): Promise<outputs.contactlists.ListContactProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:contactlists:listContact", {
        "contactlistId": args.contactlistId,
    }, opts);
}

export interface ListContactArgs {
    /**
     * The ID of the Contact List
     */
    contactlistId: string;
}
export function listContactOutput(args: ListContactOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.contactlists.ListContactProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:contactlists:listContact", {
        "contactlistId": args.contactlistId,
    }, opts);
}

export interface ListContactOutputArgs {
    /**
     * The ID of the Contact List
     */
    contactlistId: pulumi.Input<string>;
}
