// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listContactEmail(args: ListContactEmailArgs, opts?: pulumi.InvokeOptions): Promise<outputs.contactlists.ListContactEmailProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:contactlists:listContactEmail", {
        "contactlistId": args.contactlistId,
        "id": args.id,
    }, opts);
}

export interface ListContactEmailArgs {
    /**
     * The ID of the Contact List
     */
    contactlistId: string;
    /**
     * The ID of the email address
     */
    id: string;
}
export function listContactEmailOutput(args: ListContactEmailOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.contactlists.ListContactEmailProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:contactlists:listContactEmail", {
        "contactlistId": args.contactlistId,
        "id": args.id,
    }, opts);
}

export interface ListContactEmailOutputArgs {
    /**
     * The ID of the Contact List
     */
    contactlistId: pulumi.Input<string>;
    /**
     * The ID of the email address
     */
    id: pulumi.Input<string>;
}
