// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package templates

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Caa struct {
	pulumi.CustomResourceState

	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts pulumi.IntArrayOutput   `pulumi:"contacts"`
	Data     DataPropertiesPtrOutput `pulumi:"data"`
	// Whether the record is enabled
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover pulumi.BoolPtrOutput `pulumi:"geoFailover"`
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity pulumi.IntPtrOutput `pulumi:"geoproximity"`
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter pulumi.IntPtrOutput `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop pulumi.BoolPtrOutput `pulumi:"ipfilterDrop"`
	// The current mode for this record
	Mode CaaPropertiesModePtrOutput `pulumi:"mode"`
	// The name for the record
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// A description of the record. It must be 512 characters or less.
	Notes pulumi.StringPtrOutput `pulumi:"notes"`
	// Optional region for this record. Will default to 'default'.
	Region RecordCreateDetailsRegionPtrOutput `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup pulumi.BoolPtrOutput `pulumi:"skipLookup"`
	// How long DNS servers should cache the record for
	Ttl pulumi.IntPtrOutput `pulumi:"ttl"`
	// The type of record
	Type CaaPropertiesTypePtrOutput `pulumi:"type"`
	// Standard record mode
	Value ValueCaaValueItemPropertiesArrayOutput `pulumi:"value"`
}

// NewCaa registers a new resource with the given unique name, arguments, and options.
func NewCaa(ctx *pulumi.Context,
	name string, args *CaaArgs, opts ...pulumi.ResourceOption) (*Caa, error) {
	if args == nil {
		args = &CaaArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Caa
	err := ctx.RegisterResource("constellix:templates:Caa", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCaa gets an existing Caa resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCaa(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CaaState, opts ...pulumi.ResourceOption) (*Caa, error) {
	var resource Caa
	err := ctx.ReadResource("constellix:templates:Caa", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Caa resources.
type caaState struct {
}

type CaaState struct {
}

func (CaaState) ElementType() reflect.Type {
	return reflect.TypeOf((*caaState)(nil)).Elem()
}

type caaArgs struct {
	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts []int `pulumi:"contacts"`
	// Whether the record is enabled
	Enabled *bool `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover *bool `pulumi:"geoFailover"`
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity *int `pulumi:"geoproximity"`
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter *int `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop *bool `pulumi:"ipfilterDrop"`
	// The current mode for this record
	Mode *CaaPropertiesMode `pulumi:"mode"`
	// The name for the record
	Name *string `pulumi:"name"`
	// A description of the record. It must be 512 characters or less.
	Notes *string `pulumi:"notes"`
	// Optional region for this record. Will default to 'default'.
	Region *RecordCreateDetailsRegion `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup *bool `pulumi:"skipLookup"`
	// The ID of the template object
	TemplateId *string `pulumi:"templateId"`
	// How long DNS servers should cache the record for
	Ttl *int `pulumi:"ttl"`
	// The type of record
	Type *CaaPropertiesType `pulumi:"type"`
	// Standard record mode
	Value []ValueCaaValueItemProperties `pulumi:"value"`
}

// The set of arguments for constructing a Caa resource.
type CaaArgs struct {
	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts pulumi.IntArrayInput
	// Whether the record is enabled
	Enabled pulumi.BoolPtrInput
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover pulumi.BoolPtrInput
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity pulumi.IntPtrInput
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter pulumi.IntPtrInput
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop pulumi.BoolPtrInput
	// The current mode for this record
	Mode CaaPropertiesModePtrInput
	// The name for the record
	Name pulumi.StringPtrInput
	// A description of the record. It must be 512 characters or less.
	Notes pulumi.StringPtrInput
	// Optional region for this record. Will default to 'default'.
	Region RecordCreateDetailsRegionPtrInput
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup pulumi.BoolPtrInput
	// The ID of the template object
	TemplateId pulumi.StringPtrInput
	// How long DNS servers should cache the record for
	Ttl pulumi.IntPtrInput
	// The type of record
	Type CaaPropertiesTypePtrInput
	// Standard record mode
	Value ValueCaaValueItemPropertiesArrayInput
}

func (CaaArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*caaArgs)(nil)).Elem()
}

type CaaInput interface {
	pulumi.Input

	ToCaaOutput() CaaOutput
	ToCaaOutputWithContext(ctx context.Context) CaaOutput
}

func (*Caa) ElementType() reflect.Type {
	return reflect.TypeOf((**Caa)(nil)).Elem()
}

func (i *Caa) ToCaaOutput() CaaOutput {
	return i.ToCaaOutputWithContext(context.Background())
}

func (i *Caa) ToCaaOutputWithContext(ctx context.Context) CaaOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CaaOutput)
}

type CaaOutput struct{ *pulumi.OutputState }

func (CaaOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Caa)(nil)).Elem()
}

func (o CaaOutput) ToCaaOutput() CaaOutput {
	return o
}

func (o CaaOutput) ToCaaOutputWithContext(ctx context.Context) CaaOutput {
	return o
}

// Contact lists to be notified if a failover happens in a failover mode.
func (o CaaOutput) Contacts() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Caa) pulumi.IntArrayOutput { return v.Contacts }).(pulumi.IntArrayOutput)
}

func (o CaaOutput) Data() DataPropertiesPtrOutput {
	return o.ApplyT(func(v *Caa) DataPropertiesPtrOutput { return v.Data }).(DataPropertiesPtrOutput)
}

// Whether the record is enabled
func (o CaaOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
func (o CaaOutput) GeoFailover() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.BoolPtrOutput { return v.GeoFailover }).(pulumi.BoolPtrOutput)
}

// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
func (o CaaOutput) Geoproximity() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.IntPtrOutput { return v.Geoproximity }).(pulumi.IntPtrOutput)
}

// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
func (o CaaOutput) Ipfilter() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.IntPtrOutput { return v.Ipfilter }).(pulumi.IntPtrOutput)
}

// If the requesting IP matches the IP filter, don't return a response
func (o CaaOutput) IpfilterDrop() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.BoolPtrOutput { return v.IpfilterDrop }).(pulumi.BoolPtrOutput)
}

// The current mode for this record
func (o CaaOutput) Mode() CaaPropertiesModePtrOutput {
	return o.ApplyT(func(v *Caa) CaaPropertiesModePtrOutput { return v.Mode }).(CaaPropertiesModePtrOutput)
}

// The name for the record
func (o CaaOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// A description of the record. It must be 512 characters or less.
func (o CaaOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.StringPtrOutput { return v.Notes }).(pulumi.StringPtrOutput)
}

// Optional region for this record. Will default to 'default'.
func (o CaaOutput) Region() RecordCreateDetailsRegionPtrOutput {
	return o.ApplyT(func(v *Caa) RecordCreateDetailsRegionPtrOutput { return v.Region }).(RecordCreateDetailsRegionPtrOutput)
}

// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
func (o CaaOutput) SkipLookup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.BoolPtrOutput { return v.SkipLookup }).(pulumi.BoolPtrOutput)
}

// How long DNS servers should cache the record for
func (o CaaOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Caa) pulumi.IntPtrOutput { return v.Ttl }).(pulumi.IntPtrOutput)
}

// The type of record
func (o CaaOutput) Type() CaaPropertiesTypePtrOutput {
	return o.ApplyT(func(v *Caa) CaaPropertiesTypePtrOutput { return v.Type }).(CaaPropertiesTypePtrOutput)
}

// Standard record mode
func (o CaaOutput) Value() ValueCaaValueItemPropertiesArrayOutput {
	return o.ApplyT(func(v *Caa) ValueCaaValueItemPropertiesArrayOutput { return v.Value }).(ValueCaaValueItemPropertiesArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CaaInput)(nil)).Elem(), &Caa{})
	pulumi.RegisterOutputType(CaaOutput{})
}
