// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package templates

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNAPTR(ctx *pulumi.Context, args *LookupNAPTRArgs, opts ...pulumi.InvokeOption) (*LookupNAPTRResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNAPTRResult
	err := ctx.Invoke("constellix:templates:getNAPTR", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupNAPTRArgs struct {
	// The ID of the record
	Id string `pulumi:"id"`
	// The ID of the template object
	TemplateId string `pulumi:"templateId"`
}

type LookupNAPTRResult struct {
	// A simple version of a contact list when inclued with other resources
	Contacts *SimpleContactlist `pulumi:"contacts"`
	Domain   *SimpleDomain      `pulumi:"domain"`
	// Whether the record is enabled or not. A disabled record will return an NXDOMAIN response.
	Enabled *bool `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover *bool `pulumi:"geoFailover"`
	// Geo Proximity Location
	Geoproximity *SimpleGeoproximity `pulumi:"geoproximity"`
	// A unique ID for this domain record
	Id       *int            `pulumi:"id"`
	Ipfilter *SimpleIpfilter `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop *bool `pulumi:"ipfilterDrop"`
	// The previous values of the record in the different modes
	LastValues *GetNAPTRPropertiesLastValuesProperties `pulumi:"lastValues"`
	// Links for the domain record
	Links *TemplaterecordLinksProperties `pulumi:"links"`
	// How the record should work
	Mode *GetNAPTRPropertiesMode `pulumi:"mode"`
	// The name of the record
	Name *string `pulumi:"name"`
	// A note about the record. Max 512 characters.
	Notes *string `pulumi:"notes"`
	// The region for this record
	Region *RecordRegion `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup *bool           `pulumi:"skipLookup"`
	Template   *SimpleTemplate `pulumi:"template"`
	// The time to live in seconds for this record. must be between 0 and 2147483647
	Ttl *int `pulumi:"ttl"`
	// The type of record
	Type *GetNAPTRPropertiesType `pulumi:"type"`
	// Standard record mode
	Value []ValueNaptrValueItemProperties `pulumi:"value"`
}

func LookupNAPTROutput(ctx *pulumi.Context, args LookupNAPTROutputArgs, opts ...pulumi.InvokeOption) LookupNAPTRResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNAPTRResultOutput, error) {
			args := v.(LookupNAPTRArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupNAPTRResult
			secret, err := ctx.InvokePackageRaw("constellix:templates:getNAPTR", args, &rv, "", opts...)
			if err != nil {
				return LookupNAPTRResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupNAPTRResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupNAPTRResultOutput), nil
			}
			return output, nil
		}).(LookupNAPTRResultOutput)
}

type LookupNAPTROutputArgs struct {
	// The ID of the record
	Id pulumi.StringInput `pulumi:"id"`
	// The ID of the template object
	TemplateId pulumi.StringInput `pulumi:"templateId"`
}

func (LookupNAPTROutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNAPTRArgs)(nil)).Elem()
}

type LookupNAPTRResultOutput struct{ *pulumi.OutputState }

func (LookupNAPTRResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNAPTRResult)(nil)).Elem()
}

func (o LookupNAPTRResultOutput) ToLookupNAPTRResultOutput() LookupNAPTRResultOutput {
	return o
}

func (o LookupNAPTRResultOutput) ToLookupNAPTRResultOutputWithContext(ctx context.Context) LookupNAPTRResultOutput {
	return o
}

// A simple version of a contact list when inclued with other resources
func (o LookupNAPTRResultOutput) Contacts() SimpleContactlistPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *SimpleContactlist { return v.Contacts }).(SimpleContactlistPtrOutput)
}

func (o LookupNAPTRResultOutput) Domain() SimpleDomainPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *SimpleDomain { return v.Domain }).(SimpleDomainPtrOutput)
}

// Whether the record is enabled or not. A disabled record will return an NXDOMAIN response.
func (o LookupNAPTRResultOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
func (o LookupNAPTRResultOutput) GeoFailover() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *bool { return v.GeoFailover }).(pulumi.BoolPtrOutput)
}

// Geo Proximity Location
func (o LookupNAPTRResultOutput) Geoproximity() SimpleGeoproximityPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *SimpleGeoproximity { return v.Geoproximity }).(SimpleGeoproximityPtrOutput)
}

// A unique ID for this domain record
func (o LookupNAPTRResultOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o LookupNAPTRResultOutput) Ipfilter() SimpleIpfilterPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *SimpleIpfilter { return v.Ipfilter }).(SimpleIpfilterPtrOutput)
}

// If the requesting IP matches the IP filter, don't return a response
func (o LookupNAPTRResultOutput) IpfilterDrop() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *bool { return v.IpfilterDrop }).(pulumi.BoolPtrOutput)
}

// The previous values of the record in the different modes
func (o LookupNAPTRResultOutput) LastValues() GetNAPTRPropertiesLastValuesPropertiesPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *GetNAPTRPropertiesLastValuesProperties { return v.LastValues }).(GetNAPTRPropertiesLastValuesPropertiesPtrOutput)
}

// Links for the domain record
func (o LookupNAPTRResultOutput) Links() TemplaterecordLinksPropertiesPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *TemplaterecordLinksProperties { return v.Links }).(TemplaterecordLinksPropertiesPtrOutput)
}

// How the record should work
func (o LookupNAPTRResultOutput) Mode() GetNAPTRPropertiesModePtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *GetNAPTRPropertiesMode { return v.Mode }).(GetNAPTRPropertiesModePtrOutput)
}

// The name of the record
func (o LookupNAPTRResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// A note about the record. Max 512 characters.
func (o LookupNAPTRResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

// The region for this record
func (o LookupNAPTRResultOutput) Region() RecordRegionPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *RecordRegion { return v.Region }).(RecordRegionPtrOutput)
}

// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
func (o LookupNAPTRResultOutput) SkipLookup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *bool { return v.SkipLookup }).(pulumi.BoolPtrOutput)
}

func (o LookupNAPTRResultOutput) Template() SimpleTemplatePtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *SimpleTemplate { return v.Template }).(SimpleTemplatePtrOutput)
}

// The time to live in seconds for this record. must be between 0 and 2147483647
func (o LookupNAPTRResultOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *int { return v.Ttl }).(pulumi.IntPtrOutput)
}

// The type of record
func (o LookupNAPTRResultOutput) Type() GetNAPTRPropertiesTypePtrOutput {
	return o.ApplyT(func(v LookupNAPTRResult) *GetNAPTRPropertiesType { return v.Type }).(GetNAPTRPropertiesTypePtrOutput)
}

// Standard record mode
func (o LookupNAPTRResultOutput) Value() ValueNaptrValueItemPropertiesArrayOutput {
	return o.ApplyT(func(v LookupNAPTRResult) []ValueNaptrValueItemProperties { return v.Value }).(ValueNaptrValueItemPropertiesArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNAPTRResultOutput{})
}
