// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domains

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCERT(ctx *pulumi.Context, args *LookupCERTArgs, opts ...pulumi.InvokeOption) (*LookupCERTResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCERTResult
	err := ctx.Invoke("constellix:domains:getCERT", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupCERTArgs struct {
	// The ID of the domain object
	DomainId string `pulumi:"domainId"`
	// The ID of the record
	Id string `pulumi:"id"`
}

type LookupCERTResult struct {
	// A simple version of a contact list when inclued with other resources
	Contacts *SimpleContactlist `pulumi:"contacts"`
	Domain   *SimpleDomain      `pulumi:"domain"`
	// Whether the record is enabled or not. A disabled record will return an NXDOMAIN response.
	Enabled *bool `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover *bool `pulumi:"geoFailover"`
	// Geo Proximity Location
	Geoproximity *SimpleGeoproximity `pulumi:"geoproximity"`
	// A unique ID for this domain record
	Id       *int            `pulumi:"id"`
	Ipfilter *SimpleIpfilter `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop *bool `pulumi:"ipfilterDrop"`
	// The previous values of the record in the different modes
	LastValues *GetCERTPropertiesLastValuesProperties `pulumi:"lastValues"`
	// Links for the domain record
	Links *TemplaterecordLinksProperties `pulumi:"links"`
	// How the record should work
	Mode *GetCERTPropertiesMode `pulumi:"mode"`
	// The name of the record
	Name *string `pulumi:"name"`
	// A note about the record. Max 512 characters.
	Notes *string `pulumi:"notes"`
	// The region for this record
	Region *RecordRegion `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup *bool           `pulumi:"skipLookup"`
	Template   *SimpleTemplate `pulumi:"template"`
	// The time to live in seconds for this record. must be between 0 and 2147483647
	Ttl *int `pulumi:"ttl"`
	// The type of record
	Type *GetCERTPropertiesType `pulumi:"type"`
	// Standard record mode
	Value []ValueCertValueItemProperties `pulumi:"value"`
}

func LookupCERTOutput(ctx *pulumi.Context, args LookupCERTOutputArgs, opts ...pulumi.InvokeOption) LookupCERTResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCERTResultOutput, error) {
			args := v.(LookupCERTArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupCERTResult
			secret, err := ctx.InvokePackageRaw("constellix:domains:getCERT", args, &rv, "", opts...)
			if err != nil {
				return LookupCERTResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupCERTResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupCERTResultOutput), nil
			}
			return output, nil
		}).(LookupCERTResultOutput)
}

type LookupCERTOutputArgs struct {
	// The ID of the domain object
	DomainId pulumi.StringInput `pulumi:"domainId"`
	// The ID of the record
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupCERTOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCERTArgs)(nil)).Elem()
}

type LookupCERTResultOutput struct{ *pulumi.OutputState }

func (LookupCERTResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCERTResult)(nil)).Elem()
}

func (o LookupCERTResultOutput) ToLookupCERTResultOutput() LookupCERTResultOutput {
	return o
}

func (o LookupCERTResultOutput) ToLookupCERTResultOutputWithContext(ctx context.Context) LookupCERTResultOutput {
	return o
}

// A simple version of a contact list when inclued with other resources
func (o LookupCERTResultOutput) Contacts() SimpleContactlistPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *SimpleContactlist { return v.Contacts }).(SimpleContactlistPtrOutput)
}

func (o LookupCERTResultOutput) Domain() SimpleDomainPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *SimpleDomain { return v.Domain }).(SimpleDomainPtrOutput)
}

// Whether the record is enabled or not. A disabled record will return an NXDOMAIN response.
func (o LookupCERTResultOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
func (o LookupCERTResultOutput) GeoFailover() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *bool { return v.GeoFailover }).(pulumi.BoolPtrOutput)
}

// Geo Proximity Location
func (o LookupCERTResultOutput) Geoproximity() SimpleGeoproximityPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *SimpleGeoproximity { return v.Geoproximity }).(SimpleGeoproximityPtrOutput)
}

// A unique ID for this domain record
func (o LookupCERTResultOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o LookupCERTResultOutput) Ipfilter() SimpleIpfilterPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *SimpleIpfilter { return v.Ipfilter }).(SimpleIpfilterPtrOutput)
}

// If the requesting IP matches the IP filter, don't return a response
func (o LookupCERTResultOutput) IpfilterDrop() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *bool { return v.IpfilterDrop }).(pulumi.BoolPtrOutput)
}

// The previous values of the record in the different modes
func (o LookupCERTResultOutput) LastValues() GetCERTPropertiesLastValuesPropertiesPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *GetCERTPropertiesLastValuesProperties { return v.LastValues }).(GetCERTPropertiesLastValuesPropertiesPtrOutput)
}

// Links for the domain record
func (o LookupCERTResultOutput) Links() TemplaterecordLinksPropertiesPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *TemplaterecordLinksProperties { return v.Links }).(TemplaterecordLinksPropertiesPtrOutput)
}

// How the record should work
func (o LookupCERTResultOutput) Mode() GetCERTPropertiesModePtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *GetCERTPropertiesMode { return v.Mode }).(GetCERTPropertiesModePtrOutput)
}

// The name of the record
func (o LookupCERTResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// A note about the record. Max 512 characters.
func (o LookupCERTResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

// The region for this record
func (o LookupCERTResultOutput) Region() RecordRegionPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *RecordRegion { return v.Region }).(RecordRegionPtrOutput)
}

// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
func (o LookupCERTResultOutput) SkipLookup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *bool { return v.SkipLookup }).(pulumi.BoolPtrOutput)
}

func (o LookupCERTResultOutput) Template() SimpleTemplatePtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *SimpleTemplate { return v.Template }).(SimpleTemplatePtrOutput)
}

// The time to live in seconds for this record. must be between 0 and 2147483647
func (o LookupCERTResultOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *int { return v.Ttl }).(pulumi.IntPtrOutput)
}

// The type of record
func (o LookupCERTResultOutput) Type() GetCERTPropertiesTypePtrOutput {
	return o.ApplyT(func(v LookupCERTResult) *GetCERTPropertiesType { return v.Type }).(GetCERTPropertiesTypePtrOutput)
}

// Standard record mode
func (o LookupCERTResultOutput) Value() ValueCertValueItemPropertiesArrayOutput {
	return o.ApplyT(func(v LookupCERTResult) []ValueCertValueItemProperties { return v.Value }).(ValueCertValueItemPropertiesArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCERTResultOutput{})
}
