// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domains

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDomainSnapshot(ctx *pulumi.Context, args *GetDomainSnapshotArgs, opts ...pulumi.InvokeOption) (*GetDomainSnapshotResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDomainSnapshotResult
	err := ctx.Invoke("constellix:domains:getDomainSnapshot", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDomainSnapshotArgs struct {
	// The ID of the domain object
	DomainId string `pulumi:"domainId"`
	// The version number of the snapshot
	Version string `pulumi:"version"`
}

type GetDomainSnapshotResult struct {
	Data *Domainsnapshot `pulumi:"data"`
}

func GetDomainSnapshotOutput(ctx *pulumi.Context, args GetDomainSnapshotOutputArgs, opts ...pulumi.InvokeOption) GetDomainSnapshotResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDomainSnapshotResultOutput, error) {
			args := v.(GetDomainSnapshotArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetDomainSnapshotResult
			secret, err := ctx.InvokePackageRaw("constellix:domains:getDomainSnapshot", args, &rv, "", opts...)
			if err != nil {
				return GetDomainSnapshotResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetDomainSnapshotResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetDomainSnapshotResultOutput), nil
			}
			return output, nil
		}).(GetDomainSnapshotResultOutput)
}

type GetDomainSnapshotOutputArgs struct {
	// The ID of the domain object
	DomainId pulumi.StringInput `pulumi:"domainId"`
	// The version number of the snapshot
	Version pulumi.StringInput `pulumi:"version"`
}

func (GetDomainSnapshotOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainSnapshotArgs)(nil)).Elem()
}

type GetDomainSnapshotResultOutput struct{ *pulumi.OutputState }

func (GetDomainSnapshotResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainSnapshotResult)(nil)).Elem()
}

func (o GetDomainSnapshotResultOutput) ToGetDomainSnapshotResultOutput() GetDomainSnapshotResultOutput {
	return o
}

func (o GetDomainSnapshotResultOutput) ToGetDomainSnapshotResultOutputWithContext(ctx context.Context) GetDomainSnapshotResultOutput {
	return o
}

func (o GetDomainSnapshotResultOutput) Data() DomainsnapshotPtrOutput {
	return o.ApplyT(func(v GetDomainSnapshotResult) *Domainsnapshot { return v.Data }).(DomainsnapshotPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDomainSnapshotResultOutput{})
}
