// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domains

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListDomainRecords(ctx *pulumi.Context, args *ListDomainRecordsArgs, opts ...pulumi.InvokeOption) (*ListDomainRecordsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListDomainRecordsResult
	err := ctx.Invoke("constellix:domains:listDomainRecords", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListDomainRecordsArgs struct {
	// The ID of the domain object
	DomainId string `pulumi:"domainId"`
}

type ListDomainRecordsResult struct {
	// The records for this page
	Data []ListDomainRecordsPropertiesDataItem `pulumi:"data"`
	// Metadata for list responses
	Meta *ListMetadata `pulumi:"meta"`
}

func ListDomainRecordsOutput(ctx *pulumi.Context, args ListDomainRecordsOutputArgs, opts ...pulumi.InvokeOption) ListDomainRecordsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListDomainRecordsResultOutput, error) {
			args := v.(ListDomainRecordsArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv ListDomainRecordsResult
			secret, err := ctx.InvokePackageRaw("constellix:domains:listDomainRecords", args, &rv, "", opts...)
			if err != nil {
				return ListDomainRecordsResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(ListDomainRecordsResultOutput)
			if secret {
				return pulumi.ToSecret(output).(ListDomainRecordsResultOutput), nil
			}
			return output, nil
		}).(ListDomainRecordsResultOutput)
}

type ListDomainRecordsOutputArgs struct {
	// The ID of the domain object
	DomainId pulumi.StringInput `pulumi:"domainId"`
}

func (ListDomainRecordsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListDomainRecordsArgs)(nil)).Elem()
}

type ListDomainRecordsResultOutput struct{ *pulumi.OutputState }

func (ListDomainRecordsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListDomainRecordsResult)(nil)).Elem()
}

func (o ListDomainRecordsResultOutput) ToListDomainRecordsResultOutput() ListDomainRecordsResultOutput {
	return o
}

func (o ListDomainRecordsResultOutput) ToListDomainRecordsResultOutputWithContext(ctx context.Context) ListDomainRecordsResultOutput {
	return o
}

// The records for this page
func (o ListDomainRecordsResultOutput) Data() ListDomainRecordsPropertiesDataItemArrayOutput {
	return o.ApplyT(func(v ListDomainRecordsResult) []ListDomainRecordsPropertiesDataItem { return v.Data }).(ListDomainRecordsPropertiesDataItemArrayOutput)
}

// Metadata for list responses
func (o ListDomainRecordsResultOutput) Meta() ListMetadataPtrOutput {
	return o.ApplyT(func(v ListDomainRecordsResult) *ListMetadata { return v.Meta }).(ListMetadataPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ListDomainRecordsResultOutput{})
}
