// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domains

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Txt struct {
	pulumi.CustomResourceState

	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts pulumi.IntArrayOutput   `pulumi:"contacts"`
	Data     DataPropertiesPtrOutput `pulumi:"data"`
	// Whether the record is enabled
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover pulumi.BoolPtrOutput `pulumi:"geoFailover"`
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity pulumi.IntPtrOutput `pulumi:"geoproximity"`
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter pulumi.IntPtrOutput `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop pulumi.BoolPtrOutput `pulumi:"ipfilterDrop"`
	// The current mode for this record
	Mode TxtPropertiesModePtrOutput `pulumi:"mode"`
	// The name for the record
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// A description of the record. It must be 512 characters or less.
	Notes pulumi.StringPtrOutput `pulumi:"notes"`
	// Optional region for this record. Will default to 'default'.
	Region RecordCreateDetailsRegionPtrOutput `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup pulumi.BoolPtrOutput `pulumi:"skipLookup"`
	// How long DNS servers should cache the record for
	Ttl pulumi.IntPtrOutput `pulumi:"ttl"`
	// The type of record
	Type TxtPropertiesTypePtrOutput `pulumi:"type"`
	// Standard record mode
	Value ValueTxtValueItemPropertiesArrayOutput `pulumi:"value"`
}

// NewTxt registers a new resource with the given unique name, arguments, and options.
func NewTxt(ctx *pulumi.Context,
	name string, args *TxtArgs, opts ...pulumi.ResourceOption) (*Txt, error) {
	if args == nil {
		args = &TxtArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Txt
	err := ctx.RegisterResource("constellix:domains:Txt", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTxt gets an existing Txt resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTxt(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TxtState, opts ...pulumi.ResourceOption) (*Txt, error) {
	var resource Txt
	err := ctx.ReadResource("constellix:domains:Txt", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Txt resources.
type txtState struct {
}

type TxtState struct {
}

func (TxtState) ElementType() reflect.Type {
	return reflect.TypeOf((*txtState)(nil)).Elem()
}

type txtArgs struct {
	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts []int `pulumi:"contacts"`
	// The ID of the domain object
	DomainId *string `pulumi:"domainId"`
	// Whether the record is enabled
	Enabled *bool `pulumi:"enabled"`
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover *bool `pulumi:"geoFailover"`
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity *int `pulumi:"geoproximity"`
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter *int `pulumi:"ipfilter"`
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop *bool `pulumi:"ipfilterDrop"`
	// The current mode for this record
	Mode *TxtPropertiesMode `pulumi:"mode"`
	// The name for the record
	Name *string `pulumi:"name"`
	// A description of the record. It must be 512 characters or less.
	Notes *string `pulumi:"notes"`
	// Optional region for this record. Will default to 'default'.
	Region *RecordCreateDetailsRegion `pulumi:"region"`
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup *bool `pulumi:"skipLookup"`
	// How long DNS servers should cache the record for
	Ttl *int `pulumi:"ttl"`
	// The type of record
	Type *TxtPropertiesType `pulumi:"type"`
	// Standard record mode
	Value []ValueTxtValueItemProperties `pulumi:"value"`
}

// The set of arguments for constructing a Txt resource.
type TxtArgs struct {
	// Contact lists to be notified if a failover happens in a failover mode.
	Contacts pulumi.IntArrayInput
	// The ID of the domain object
	DomainId pulumi.StringPtrInput
	// Whether the record is enabled
	Enabled pulumi.BoolPtrInput
	// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
	GeoFailover pulumi.BoolPtrInput
	// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
	Geoproximity pulumi.IntPtrInput
	// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
	Ipfilter pulumi.IntPtrInput
	// If the requesting IP matches the IP filter, don't return a response
	IpfilterDrop pulumi.BoolPtrInput
	// The current mode for this record
	Mode TxtPropertiesModePtrInput
	// The name for the record
	Name pulumi.StringPtrInput
	// A description of the record. It must be 512 characters or less.
	Notes pulumi.StringPtrInput
	// Optional region for this record. Will default to 'default'.
	Region RecordCreateDetailsRegionPtrInput
	// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
	SkipLookup pulumi.BoolPtrInput
	// How long DNS servers should cache the record for
	Ttl pulumi.IntPtrInput
	// The type of record
	Type TxtPropertiesTypePtrInput
	// Standard record mode
	Value ValueTxtValueItemPropertiesArrayInput
}

func (TxtArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*txtArgs)(nil)).Elem()
}

type TxtInput interface {
	pulumi.Input

	ToTxtOutput() TxtOutput
	ToTxtOutputWithContext(ctx context.Context) TxtOutput
}

func (*Txt) ElementType() reflect.Type {
	return reflect.TypeOf((**Txt)(nil)).Elem()
}

func (i *Txt) ToTxtOutput() TxtOutput {
	return i.ToTxtOutputWithContext(context.Background())
}

func (i *Txt) ToTxtOutputWithContext(ctx context.Context) TxtOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TxtOutput)
}

type TxtOutput struct{ *pulumi.OutputState }

func (TxtOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Txt)(nil)).Elem()
}

func (o TxtOutput) ToTxtOutput() TxtOutput {
	return o
}

func (o TxtOutput) ToTxtOutputWithContext(ctx context.Context) TxtOutput {
	return o
}

// Contact lists to be notified if a failover happens in a failover mode.
func (o TxtOutput) Contacts() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Txt) pulumi.IntArrayOutput { return v.Contacts }).(pulumi.IntArrayOutput)
}

func (o TxtOutput) Data() DataPropertiesPtrOutput {
	return o.ApplyT(func(v *Txt) DataPropertiesPtrOutput { return v.Data }).(DataPropertiesPtrOutput)
}

// Whether the record is enabled
func (o TxtOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// Disable the record if all hosts fail. If all hosts fail, another matching IP Filter, nearest Proximity or World (Default) record will be used instead.
func (o TxtOutput) GeoFailover() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.BoolPtrOutput { return v.GeoFailover }).(pulumi.BoolPtrOutput)
}

// The integer ID of a GeoProximity to use for this record. Cannot be used with IP Filter.
func (o TxtOutput) Geoproximity() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.IntPtrOutput { return v.Geoproximity }).(pulumi.IntPtrOutput)
}

// The integer ID of an IP Filter to use for this record. Cannot be used with GeoPeoximity.
func (o TxtOutput) Ipfilter() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.IntPtrOutput { return v.Ipfilter }).(pulumi.IntPtrOutput)
}

// If the requesting IP matches the IP filter, don't return a response
func (o TxtOutput) IpfilterDrop() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.BoolPtrOutput { return v.IpfilterDrop }).(pulumi.BoolPtrOutput)
}

// The current mode for this record
func (o TxtOutput) Mode() TxtPropertiesModePtrOutput {
	return o.ApplyT(func(v *Txt) TxtPropertiesModePtrOutput { return v.Mode }).(TxtPropertiesModePtrOutput)
}

// The name for the record
func (o TxtOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// A description of the record. It must be 512 characters or less.
func (o TxtOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.StringPtrOutput { return v.Notes }).(pulumi.StringPtrOutput)
}

// Optional region for this record. Will default to 'default'.
func (o TxtOutput) Region() RecordCreateDetailsRegionPtrOutput {
	return o.ApplyT(func(v *Txt) RecordCreateDetailsRegionPtrOutput { return v.Region }).(RecordCreateDetailsRegionPtrOutput)
}

// Only used on POST or PATCH requests for ANAME records, used to specify whether the hostname should be looked up immediately. Will be null otherwise.
func (o TxtOutput) SkipLookup() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.BoolPtrOutput { return v.SkipLookup }).(pulumi.BoolPtrOutput)
}

// How long DNS servers should cache the record for
func (o TxtOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Txt) pulumi.IntPtrOutput { return v.Ttl }).(pulumi.IntPtrOutput)
}

// The type of record
func (o TxtOutput) Type() TxtPropertiesTypePtrOutput {
	return o.ApplyT(func(v *Txt) TxtPropertiesTypePtrOutput { return v.Type }).(TxtPropertiesTypePtrOutput)
}

// Standard record mode
func (o TxtOutput) Value() ValueTxtValueItemPropertiesArrayOutput {
	return o.ApplyT(func(v *Txt) ValueTxtValueItemPropertiesArrayOutput { return v.Value }).(ValueTxtValueItemPropertiesArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TxtInput)(nil)).Elem(), &Txt{})
	pulumi.RegisterOutputType(TxtOutput{})
}
