// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Contactlists.Outputs
{

    [OutputType]
    public sealed class ContactlistTeamsContactlistProperties
    {
        /// <summary>
        /// Unique ID for the contact list
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Links for the contact list
        /// </summary>
        public readonly Outputs.ContactlistTeamsContactlistPropertiesLinksProperties? Links;

        [OutputConstructor]
        private ContactlistTeamsContactlistProperties(
            int? id,

            Outputs.ContactlistTeamsContactlistPropertiesLinksProperties? links)
        {
            Id = id;
            Links = links;
        }
    }
}
