// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CONSTELLIX.Contactlists.Outputs
{

    [OutputType]
    public sealed class ContactlistEmail
    {
        public readonly string? Address;
        public readonly Outputs.ContactlistEmailContactlistProperties? Contactlist;
        public readonly int? Id;
        /// <summary>
        /// Links for the email address
        /// </summary>
        public readonly Outputs.ContactlistEmailLinksProperties? Links;
        /// <summary>
        /// Has the email been verified or not
        /// </summary>
        public readonly bool? Verified;

        [OutputConstructor]
        private ContactlistEmail(
            string? address,

            Outputs.ContactlistEmailContactlistProperties? contactlist,

            int? id,

            Outputs.ContactlistEmailLinksProperties? links,

            bool? verified)
        {
            Address = address;
            Contactlist = contactlist;
            Id = id;
            Links = links;
            Verified = verified;
        }
    }
}
