# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetGeoProximityLocationProperties',
    'AwaitableGetGeoProximityLocationProperties',
    'get_geo_proximity_location',
    'get_geo_proximity_location_output',
]

@pulumi.output_type
class GetGeoProximityLocationProperties:
    def __init__(__self__, data=None):
        if data and not isinstance(data, dict):
            raise TypeError("Expected argument 'data' to be a dict")
        pulumi.set(__self__, "data", data)

    @property
    @pulumi.getter
    def data(self) -> Optional['outputs.Geoproximity']:
        """
        Geo Proximity Location
        """
        return pulumi.get(self, "data")


class AwaitableGetGeoProximityLocationProperties(GetGeoProximityLocationProperties):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGeoProximityLocationProperties(
            data=self.data)


def get_geo_proximity_location(id: Optional[str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGeoProximityLocationProperties:
    """
    Use this data source to access information about an existing resource.

    :param str id: The ID of the Geo Proximity
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('constellix:geoproximities:getGeoProximityLocation', __args__, opts=opts, typ=GetGeoProximityLocationProperties).value

    return AwaitableGetGeoProximityLocationProperties(
        data=pulumi.get(__ret__, 'data'))
def get_geo_proximity_location_output(id: Optional[pulumi.Input[str]] = None,
                                      opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetGeoProximityLocationProperties]:
    """
    Use this data source to access information about an existing resource.

    :param str id: The ID of the Geo Proximity
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('constellix:geoproximities:getGeoProximityLocation', __args__, opts=opts, typ=GetGeoProximityLocationProperties)
    return __ret__.apply(lambda __response__: GetGeoProximityLocationProperties(
        data=pulumi.get(__response__, 'data')))
