// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package search

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-constellix/sdk/go/constellix/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

// Represents a search result when searching for domains
type Domainsearchresult struct {
	// The ID for the domain name
	Id *int `pulumi:"id"`
	// Links for domain search results
	Links *DomainsearchresultLinksProperties `pulumi:"links"`
	// The name of the domain
	Name *string `pulumi:"name"`
}

// Represents a search result when searching for domains
type DomainsearchresultOutput struct{ *pulumi.OutputState }

func (DomainsearchresultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Domainsearchresult)(nil)).Elem()
}

func (o DomainsearchresultOutput) ToDomainsearchresultOutput() DomainsearchresultOutput {
	return o
}

func (o DomainsearchresultOutput) ToDomainsearchresultOutputWithContext(ctx context.Context) DomainsearchresultOutput {
	return o
}

// The ID for the domain name
func (o DomainsearchresultOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Domainsearchresult) *int { return v.Id }).(pulumi.IntPtrOutput)
}

// Links for domain search results
func (o DomainsearchresultOutput) Links() DomainsearchresultLinksPropertiesPtrOutput {
	return o.ApplyT(func(v Domainsearchresult) *DomainsearchresultLinksProperties { return v.Links }).(DomainsearchresultLinksPropertiesPtrOutput)
}

// The name of the domain
func (o DomainsearchresultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Domainsearchresult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type DomainsearchresultArrayOutput struct{ *pulumi.OutputState }

func (DomainsearchresultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Domainsearchresult)(nil)).Elem()
}

func (o DomainsearchresultArrayOutput) ToDomainsearchresultArrayOutput() DomainsearchresultArrayOutput {
	return o
}

func (o DomainsearchresultArrayOutput) ToDomainsearchresultArrayOutputWithContext(ctx context.Context) DomainsearchresultArrayOutput {
	return o
}

func (o DomainsearchresultArrayOutput) Index(i pulumi.IntInput) DomainsearchresultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Domainsearchresult {
		return vs[0].([]Domainsearchresult)[vs[1].(int)]
	}).(DomainsearchresultOutput)
}

// Links for domain search results
type DomainsearchresultLinksProperties struct {
	Domain *string `pulumi:"domain"`
}

// Links for domain search results
type DomainsearchresultLinksPropertiesOutput struct{ *pulumi.OutputState }

func (DomainsearchresultLinksPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DomainsearchresultLinksProperties)(nil)).Elem()
}

func (o DomainsearchresultLinksPropertiesOutput) ToDomainsearchresultLinksPropertiesOutput() DomainsearchresultLinksPropertiesOutput {
	return o
}

func (o DomainsearchresultLinksPropertiesOutput) ToDomainsearchresultLinksPropertiesOutputWithContext(ctx context.Context) DomainsearchresultLinksPropertiesOutput {
	return o
}

func (o DomainsearchresultLinksPropertiesOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DomainsearchresultLinksProperties) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

type DomainsearchresultLinksPropertiesPtrOutput struct{ *pulumi.OutputState }

func (DomainsearchresultLinksPropertiesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainsearchresultLinksProperties)(nil)).Elem()
}

func (o DomainsearchresultLinksPropertiesPtrOutput) ToDomainsearchresultLinksPropertiesPtrOutput() DomainsearchresultLinksPropertiesPtrOutput {
	return o
}

func (o DomainsearchresultLinksPropertiesPtrOutput) ToDomainsearchresultLinksPropertiesPtrOutputWithContext(ctx context.Context) DomainsearchresultLinksPropertiesPtrOutput {
	return o
}

func (o DomainsearchresultLinksPropertiesPtrOutput) Elem() DomainsearchresultLinksPropertiesOutput {
	return o.ApplyT(func(v *DomainsearchresultLinksProperties) DomainsearchresultLinksProperties {
		if v != nil {
			return *v
		}
		var ret DomainsearchresultLinksProperties
		return ret
	}).(DomainsearchresultLinksPropertiesOutput)
}

func (o DomainsearchresultLinksPropertiesPtrOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainsearchresultLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.Domain
	}).(pulumi.StringPtrOutput)
}

type GetSearchDomainProperties struct {
	// The search results for this page
	Data []Domainsearchresult `pulumi:"data"`
	// Metadata for list responses
	Meta *ListMetadata `pulumi:"meta"`
}

type GetSearchDomainPropertiesOutput struct{ *pulumi.OutputState }

func (GetSearchDomainPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSearchDomainProperties)(nil)).Elem()
}

func (o GetSearchDomainPropertiesOutput) ToGetSearchDomainPropertiesOutput() GetSearchDomainPropertiesOutput {
	return o
}

func (o GetSearchDomainPropertiesOutput) ToGetSearchDomainPropertiesOutputWithContext(ctx context.Context) GetSearchDomainPropertiesOutput {
	return o
}

// The search results for this page
func (o GetSearchDomainPropertiesOutput) Data() DomainsearchresultArrayOutput {
	return o.ApplyT(func(v GetSearchDomainProperties) []Domainsearchresult { return v.Data }).(DomainsearchresultArrayOutput)
}

// Metadata for list responses
func (o GetSearchDomainPropertiesOutput) Meta() ListMetadataPtrOutput {
	return o.ApplyT(func(v GetSearchDomainProperties) *ListMetadata { return v.Meta }).(ListMetadataPtrOutput)
}

// Metadata for list responses
type ListMetadata struct {
	// Relevant links for this list
	Links *ListMetadataLinksProperties `pulumi:"links"`
	// Pagination details
	Pagination *ListMetadataPaginationProperties `pulumi:"pagination"`
}

// Metadata for list responses
type ListMetadataOutput struct{ *pulumi.OutputState }

func (ListMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListMetadata)(nil)).Elem()
}

func (o ListMetadataOutput) ToListMetadataOutput() ListMetadataOutput {
	return o
}

func (o ListMetadataOutput) ToListMetadataOutputWithContext(ctx context.Context) ListMetadataOutput {
	return o
}

// Relevant links for this list
func (o ListMetadataOutput) Links() ListMetadataLinksPropertiesPtrOutput {
	return o.ApplyT(func(v ListMetadata) *ListMetadataLinksProperties { return v.Links }).(ListMetadataLinksPropertiesPtrOutput)
}

// Pagination details
func (o ListMetadataOutput) Pagination() ListMetadataPaginationPropertiesPtrOutput {
	return o.ApplyT(func(v ListMetadata) *ListMetadataPaginationProperties { return v.Pagination }).(ListMetadataPaginationPropertiesPtrOutput)
}

type ListMetadataPtrOutput struct{ *pulumi.OutputState }

func (ListMetadataPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ListMetadata)(nil)).Elem()
}

func (o ListMetadataPtrOutput) ToListMetadataPtrOutput() ListMetadataPtrOutput {
	return o
}

func (o ListMetadataPtrOutput) ToListMetadataPtrOutputWithContext(ctx context.Context) ListMetadataPtrOutput {
	return o
}

func (o ListMetadataPtrOutput) Elem() ListMetadataOutput {
	return o.ApplyT(func(v *ListMetadata) ListMetadata {
		if v != nil {
			return *v
		}
		var ret ListMetadata
		return ret
	}).(ListMetadataOutput)
}

// Relevant links for this list
func (o ListMetadataPtrOutput) Links() ListMetadataLinksPropertiesPtrOutput {
	return o.ApplyT(func(v *ListMetadata) *ListMetadataLinksProperties {
		if v == nil {
			return nil
		}
		return v.Links
	}).(ListMetadataLinksPropertiesPtrOutput)
}

// Pagination details
func (o ListMetadataPtrOutput) Pagination() ListMetadataPaginationPropertiesPtrOutput {
	return o.ApplyT(func(v *ListMetadata) *ListMetadataPaginationProperties {
		if v == nil {
			return nil
		}
		return v.Pagination
	}).(ListMetadataPaginationPropertiesPtrOutput)
}

// Relevant links for this list
type ListMetadataLinksProperties struct {
	First    *string `pulumi:"first"`
	Last     *string `pulumi:"last"`
	Next     *string `pulumi:"next"`
	Previous *string `pulumi:"previous"`
	Self     *string `pulumi:"self"`
}

// Relevant links for this list
type ListMetadataLinksPropertiesOutput struct{ *pulumi.OutputState }

func (ListMetadataLinksPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListMetadataLinksProperties)(nil)).Elem()
}

func (o ListMetadataLinksPropertiesOutput) ToListMetadataLinksPropertiesOutput() ListMetadataLinksPropertiesOutput {
	return o
}

func (o ListMetadataLinksPropertiesOutput) ToListMetadataLinksPropertiesOutputWithContext(ctx context.Context) ListMetadataLinksPropertiesOutput {
	return o
}

func (o ListMetadataLinksPropertiesOutput) First() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListMetadataLinksProperties) *string { return v.First }).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesOutput) Last() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListMetadataLinksProperties) *string { return v.Last }).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesOutput) Next() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListMetadataLinksProperties) *string { return v.Next }).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesOutput) Previous() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListMetadataLinksProperties) *string { return v.Previous }).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesOutput) Self() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListMetadataLinksProperties) *string { return v.Self }).(pulumi.StringPtrOutput)
}

type ListMetadataLinksPropertiesPtrOutput struct{ *pulumi.OutputState }

func (ListMetadataLinksPropertiesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ListMetadataLinksProperties)(nil)).Elem()
}

func (o ListMetadataLinksPropertiesPtrOutput) ToListMetadataLinksPropertiesPtrOutput() ListMetadataLinksPropertiesPtrOutput {
	return o
}

func (o ListMetadataLinksPropertiesPtrOutput) ToListMetadataLinksPropertiesPtrOutputWithContext(ctx context.Context) ListMetadataLinksPropertiesPtrOutput {
	return o
}

func (o ListMetadataLinksPropertiesPtrOutput) Elem() ListMetadataLinksPropertiesOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) ListMetadataLinksProperties {
		if v != nil {
			return *v
		}
		var ret ListMetadataLinksProperties
		return ret
	}).(ListMetadataLinksPropertiesOutput)
}

func (o ListMetadataLinksPropertiesPtrOutput) First() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.First
	}).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesPtrOutput) Last() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.Last
	}).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesPtrOutput) Next() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.Next
	}).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesPtrOutput) Previous() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.Previous
	}).(pulumi.StringPtrOutput)
}

func (o ListMetadataLinksPropertiesPtrOutput) Self() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ListMetadataLinksProperties) *string {
		if v == nil {
			return nil
		}
		return v.Self
	}).(pulumi.StringPtrOutput)
}

// Pagination details
type ListMetadataPaginationProperties struct {
	// The number of items in this page of the response
	Count *int `pulumi:"count"`
	// The current results page
	CurrentPage *int `pulumi:"currentPage"`
	// The number of items per page
	PerPage *int `pulumi:"perPage"`
	// The total number of objects matching the query
	Total *int `pulumi:"total"`
	// The total number of pages
	TotalPages *int `pulumi:"totalPages"`
}

// Pagination details
type ListMetadataPaginationPropertiesOutput struct{ *pulumi.OutputState }

func (ListMetadataPaginationPropertiesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListMetadataPaginationProperties)(nil)).Elem()
}

func (o ListMetadataPaginationPropertiesOutput) ToListMetadataPaginationPropertiesOutput() ListMetadataPaginationPropertiesOutput {
	return o
}

func (o ListMetadataPaginationPropertiesOutput) ToListMetadataPaginationPropertiesOutputWithContext(ctx context.Context) ListMetadataPaginationPropertiesOutput {
	return o
}

// The number of items in this page of the response
func (o ListMetadataPaginationPropertiesOutput) Count() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListMetadataPaginationProperties) *int { return v.Count }).(pulumi.IntPtrOutput)
}

// The current results page
func (o ListMetadataPaginationPropertiesOutput) CurrentPage() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListMetadataPaginationProperties) *int { return v.CurrentPage }).(pulumi.IntPtrOutput)
}

// The number of items per page
func (o ListMetadataPaginationPropertiesOutput) PerPage() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListMetadataPaginationProperties) *int { return v.PerPage }).(pulumi.IntPtrOutput)
}

// The total number of objects matching the query
func (o ListMetadataPaginationPropertiesOutput) Total() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListMetadataPaginationProperties) *int { return v.Total }).(pulumi.IntPtrOutput)
}

// The total number of pages
func (o ListMetadataPaginationPropertiesOutput) TotalPages() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListMetadataPaginationProperties) *int { return v.TotalPages }).(pulumi.IntPtrOutput)
}

type ListMetadataPaginationPropertiesPtrOutput struct{ *pulumi.OutputState }

func (ListMetadataPaginationPropertiesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ListMetadataPaginationProperties)(nil)).Elem()
}

func (o ListMetadataPaginationPropertiesPtrOutput) ToListMetadataPaginationPropertiesPtrOutput() ListMetadataPaginationPropertiesPtrOutput {
	return o
}

func (o ListMetadataPaginationPropertiesPtrOutput) ToListMetadataPaginationPropertiesPtrOutputWithContext(ctx context.Context) ListMetadataPaginationPropertiesPtrOutput {
	return o
}

func (o ListMetadataPaginationPropertiesPtrOutput) Elem() ListMetadataPaginationPropertiesOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) ListMetadataPaginationProperties {
		if v != nil {
			return *v
		}
		var ret ListMetadataPaginationProperties
		return ret
	}).(ListMetadataPaginationPropertiesOutput)
}

// The number of items in this page of the response
func (o ListMetadataPaginationPropertiesPtrOutput) Count() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) *int {
		if v == nil {
			return nil
		}
		return v.Count
	}).(pulumi.IntPtrOutput)
}

// The current results page
func (o ListMetadataPaginationPropertiesPtrOutput) CurrentPage() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) *int {
		if v == nil {
			return nil
		}
		return v.CurrentPage
	}).(pulumi.IntPtrOutput)
}

// The number of items per page
func (o ListMetadataPaginationPropertiesPtrOutput) PerPage() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) *int {
		if v == nil {
			return nil
		}
		return v.PerPage
	}).(pulumi.IntPtrOutput)
}

// The total number of objects matching the query
func (o ListMetadataPaginationPropertiesPtrOutput) Total() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) *int {
		if v == nil {
			return nil
		}
		return v.Total
	}).(pulumi.IntPtrOutput)
}

// The total number of pages
func (o ListMetadataPaginationPropertiesPtrOutput) TotalPages() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ListMetadataPaginationProperties) *int {
		if v == nil {
			return nil
		}
		return v.TotalPages
	}).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(DomainsearchresultOutput{})
	pulumi.RegisterOutputType(DomainsearchresultArrayOutput{})
	pulumi.RegisterOutputType(DomainsearchresultLinksPropertiesOutput{})
	pulumi.RegisterOutputType(DomainsearchresultLinksPropertiesPtrOutput{})
	pulumi.RegisterOutputType(GetSearchDomainPropertiesOutput{})
	pulumi.RegisterOutputType(ListMetadataOutput{})
	pulumi.RegisterOutputType(ListMetadataPtrOutput{})
	pulumi.RegisterOutputType(ListMetadataLinksPropertiesOutput{})
	pulumi.RegisterOutputType(ListMetadataLinksPropertiesPtrOutput{})
	pulumi.RegisterOutputType(ListMetadataPaginationPropertiesOutput{})
	pulumi.RegisterOutputType(ListMetadataPaginationPropertiesPtrOutput{})
}
