// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { GetPingArgs } from "./getPing";
export const getPing: typeof import("./getPing").getPing = null as any;
export const getPingOutput: typeof import("./getPing").getPingOutput = null as any;
utilities.lazyLoad(exports, ["getPing","getPingOutput"], () => require("./getPing"));

