// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Ipfilters.Outputs
{

    [OutputType]
    public sealed class RegionsItemProperties
    {
        /// <summary>
        /// Optional AS Number that this rule applies to. Values must be between 0 and 4,294,967,295
        /// </summary>
        public readonly int? Asn;
        /// <summary>
        /// The continent for this region
        /// </summary>
        public readonly CloudySkySoftware.Pulumi.Constellix.Ipfilters.RegionsItemPropertiesContinent? Continent;
        /// <summary>
        /// Optional 2 digit ISO code for the country - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
        /// </summary>
        public readonly string? Country;
        /// <summary>
        /// Optional 2 digit code for the region
        /// </summary>
        public readonly string? Region;

        [OutputConstructor]
        private RegionsItemProperties(
            int? asn,

            CloudySkySoftware.Pulumi.Constellix.Ipfilters.RegionsItemPropertiesContinent? continent,

            string? country,

            string? region)
        {
            Asn = asn;
            Continent = continent;
            Country = country;
            Region = region;
        }
    }
}
