// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains.Outputs
{

    [OutputType]
    public sealed class Domain
    {
        /// <summary>
        /// An array of contact lists that will be notified when records in this domain change.
        /// </summary>
        public readonly ImmutableArray<Outputs.SimpleContactlist> Contacts;
        public readonly string? CreatedAt;
        /// <summary>
        /// Is the domain enabled
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Is GeoIP functionality enabled for the domain
        /// </summary>
        public readonly bool? Geoip;
        /// <summary>
        /// Is Global Traffic Director enabled for the domain
        /// </summary>
        public readonly bool? Gtd;
        /// <summary>
        /// A unique numeric ID for this domain
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Links for domain objects
        /// </summary>
        public readonly Outputs.DomainLinksProperties? Links;
        /// <summary>
        /// The name of the domain
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The nameservers for the domain
        /// </summary>
        public readonly ImmutableArray<string> Nameservers;
        /// <summary>
        /// A note for the domain
        /// </summary>
        public readonly string? Note;
        /// <summary>
        /// SOA (Start of Authority) Record
        /// </summary>
        public readonly Outputs.Soa? Soa;
        public readonly CloudySkySoftware.Pulumi.Constellix.Domains.DomainStatus? Status;
        /// <summary>
        /// An array of tags for this domain.
        /// </summary>
        public readonly ImmutableArray<Outputs.Tag> Tags;
        public readonly Outputs.SimpleTemplate? Template;
        public readonly string? UpdatedAt;
        /// <summary>
        /// A simplied version of a rebranded nameserver using your own domain name.
        /// </summary>
        public readonly Outputs.SimpleVanitynameserver? VanityNameserver;
        /// <summary>
        /// The version of the domain resource
        /// </summary>
        public readonly int? Version;

        [OutputConstructor]
        private Domain(
            ImmutableArray<Outputs.SimpleContactlist> contacts,

            string? createdAt,

            bool? enabled,

            bool? geoip,

            bool? gtd,

            int? id,

            Outputs.DomainLinksProperties? links,

            string? name,

            ImmutableArray<string> nameservers,

            string? note,

            Outputs.Soa? soa,

            CloudySkySoftware.Pulumi.Constellix.Domains.DomainStatus? status,

            ImmutableArray<Outputs.Tag> tags,

            Outputs.SimpleTemplate? template,

            string? updatedAt,

            Outputs.SimpleVanitynameserver? vanityNameserver,

            int? version)
        {
            Contacts = contacts;
            CreatedAt = createdAt;
            Enabled = enabled;
            Geoip = geoip;
            Gtd = gtd;
            Id = id;
            Links = links;
            Name = name;
            Nameservers = nameservers;
            Note = note;
            Soa = soa;
            Status = status;
            Tags = tags;
            Template = template;
            UpdatedAt = updatedAt;
            VanityNameserver = vanityNameserver;
            Version = version;
        }
    }
}
