// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains.Outputs
{

    /// <summary>
    /// Analytics for a specific domain
    /// </summary>
    [OutputType]
    public sealed class Domainanalytics
    {
        public readonly Outputs.SimpleDomain? Domain;
        /// <summary>
        /// The end date for the analytics
        /// </summary>
        public readonly string? End;
        /// <summary>
        /// Details about the interval between time periods in the analytics
        /// </summary>
        public readonly Outputs.DomainanalyticsIntervalProperties? Interval;
        public readonly Outputs.DomainanalyticsLinksProperties? Links;
        /// <summary>
        /// An array of analytics data for different types of query
        /// </summary>
        public readonly ImmutableArray<Outputs.DomainanalyticsQueriesItemProperties> Queries;
        /// <summary>
        /// The start date for the analytics
        /// </summary>
        public readonly string? Start;
        /// <summary>
        /// Some statistics for these analytics
        /// </summary>
        public readonly Outputs.DomainanalyticsStatsProperties? Stats;

        [OutputConstructor]
        private Domainanalytics(
            Outputs.SimpleDomain? domain,

            string? end,

            Outputs.DomainanalyticsIntervalProperties? interval,

            Outputs.DomainanalyticsLinksProperties? links,

            ImmutableArray<Outputs.DomainanalyticsQueriesItemProperties> queries,

            string? start,

            Outputs.DomainanalyticsStatsProperties? stats)
        {
            Domain = domain;
            End = end;
            Interval = interval;
            Links = links;
            Queries = queries;
            Start = start;
            Stats = stats;
        }
    }
}
