// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains.Outputs
{

    /// <summary>
    /// Geo Proximity Location
    /// </summary>
    [OutputType]
    public sealed class SimpleGeoproximity
    {
        /// <summary>
        /// The unique ID for the Geo Proximity location
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Links for domain objects
        /// </summary>
        public readonly Outputs.SimpleGeoproximityLinksProperties? Links;
        /// <summary>
        /// The name of the Geo Proximity location
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private SimpleGeoproximity(
            int? id,

            Outputs.SimpleGeoproximityLinksProperties? links,

            string? name)
        {
            Id = id;
            Links = links;
            Name = name;
        }
    }
}
