// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CloudySkySoftware.Pulumi.Constellix.Domains.Outputs
{

    [OutputType]
    public sealed class ValueHttpValueProperties
    {
        /// <summary>
        /// The description to include in meta tags
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// If this is a frame redirect, don't include the URL entered in the browser
        /// </summary>
        public readonly bool? Hard;
        /// <summary>
        /// Meta keywords for the page containing the frame
        /// </summary>
        public readonly string? Keywords;
        /// <summary>
        /// The type of redirect, either 301, 302 or frame.
        /// </summary>
        public readonly string? RedirectType;
        /// <summary>
        /// The title of the page containing the redirect frame
        /// </summary>
        public readonly string? Title;
        /// <summary>
        /// The URL to redirect to
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private ValueHttpValueProperties(
            string? description,

            bool? hard,

            string? keywords,

            string? redirectType,

            string? title,

            string? url)
        {
            Description = description;
            Hard = hard;
            Keywords = keywords;
            RedirectType = redirectType;
            Title = title;
            Url = url;
        }
    }
}
