# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetDomainSnapshotProperties',
    'AwaitableGetDomainSnapshotProperties',
    'get_domain_snapshot',
    'get_domain_snapshot_output',
]

@pulumi.output_type
class GetDomainSnapshotProperties:
    def __init__(__self__, data=None):
        if data and not isinstance(data, dict):
            raise TypeError("Expected argument 'data' to be a dict")
        pulumi.set(__self__, "data", data)

    @property
    @pulumi.getter
    def data(self) -> Optional['outputs.Domainsnapshot']:
        return pulumi.get(self, "data")


class AwaitableGetDomainSnapshotProperties(GetDomainSnapshotProperties):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDomainSnapshotProperties(
            data=self.data)


def get_domain_snapshot(domain_id: Optional[str] = None,
                        version: Optional[str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDomainSnapshotProperties:
    """
    Use this data source to access information about an existing resource.

    :param str domain_id: The ID of the domain object
    :param str version: The version number of the snapshot
    """
    __args__ = dict()
    __args__['domainId'] = domain_id
    __args__['version'] = version
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('constellix:domains:getDomainSnapshot', __args__, opts=opts, typ=GetDomainSnapshotProperties).value

    return AwaitableGetDomainSnapshotProperties(
        data=pulumi.get(__ret__, 'data'))
def get_domain_snapshot_output(domain_id: Optional[pulumi.Input[str]] = None,
                               version: Optional[pulumi.Input[str]] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetDomainSnapshotProperties]:
    """
    Use this data source to access information about an existing resource.

    :param str domain_id: The ID of the domain object
    :param str version: The version number of the snapshot
    """
    __args__ = dict()
    __args__['domainId'] = domain_id
    __args__['version'] = version
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('constellix:domains:getDomainSnapshot', __args__, opts=opts, typ=GetDomainSnapshotProperties)
    return __ret__.apply(lambda __response__: GetDomainSnapshotProperties(
        data=pulumi.get(__response__, 'data')))
