// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getSPF(args: GetSPFArgs, opts?: pulumi.InvokeOptions): Promise<outputs.templates.GetSPF> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:templates:getSPF", {
        "id": args.id,
        "templateId": args.templateId,
    }, opts);
}

export interface GetSPFArgs {
    /**
     * The ID of the record
     */
    id: string;
    /**
     * The ID of the template object
     */
    templateId: string;
}
export function getSPFOutput(args: GetSPFOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.templates.GetSPF> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:templates:getSPF", {
        "id": args.id,
        "templateId": args.templateId,
    }, opts);
}

export interface GetSPFOutputArgs {
    /**
     * The ID of the record
     */
    id: pulumi.Input<string>;
    /**
     * The ID of the template object
     */
    templateId: pulumi.Input<string>;
}
