// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function getTemplate(args: GetTemplateArgs, opts?: pulumi.InvokeOptions): Promise<outputs.templates.GetTemplateProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("constellix:templates:getTemplate", {
        "id": args.id,
    }, opts);
}

export interface GetTemplateArgs {
    /**
     * The ID of the template object
     */
    id: string;
}
export function getTemplateOutput(args: GetTemplateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<outputs.templates.GetTemplateProperties> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("constellix:templates:getTemplate", {
        "id": args.id,
    }, opts);
}

export interface GetTemplateOutputArgs {
    /**
     * The ID of the template object
     */
    id: pulumi.Input<string>;
}
